### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by cjnething** [daniyalzade/django_reverse_admin#109]
Thanks for this project, it looks really useful!

Unfortunately it looks like the Delete button is now missing when you edit one of the parent objects. It's also missing in the screenshots in the README (the red delete button in the same row as Save, etc.).

Is there an easy way to add the Delete button back in, for example a setting that I can change?

Thanks for your help!

**Comment by daniyalzade** [comment]
Just fixed it. Apologies for the delay and glad it's helpful.

**Comment by cjnething** [comment]
@daniyalzade Thank you!
