### ISSUE TITLE
Non-editable fields should be ignored by default

### ISSUE THREAD

**Issue by akx** [daniyalzade/django_reverse_admin#13]
I have a couple non-editable fields on the models-to-be-inlined.

Right now with just a `inline_reverse = ['billing_address']` configuration I get

> 'ctime' cannot be specified for Address model form as it is a non-editable field.

Would be nice if those were ignored by default.

**Comment by daniyalzade** [comment]
Thanks raising this @akx . #15 fixes this.

**Comment by Yungbubu** [comment]
What if I want to display read_only fields ?
