### ISSUE TITLE
Tag a release version

### ISSUE THREAD

**Issue by mxreppy** [daniyalzade/django_reverse_admin#3]
Thanks!  

very helpful in a django admin update I'm working on.  

This is not necessary, but it would be helpful to tag a version for installation and possibly update the readme to describe how to use it.

**Comment by daniyalzade** [comment]
Thanks for the feedback @mxreppy . This project has been on the back-burner for quite sometime, but I am getting back addressing the issues. I just added tagging and will continue to do so. Better packaging is coming up next.
