### ISSUE TITLE
be compatible with `UserAdmin`

### ISSUE THREAD

**Issue by phith0n** [daniyalzade/django_reverse_admin#59]
Is there a way that I can use `django_reverse_admin` with Django's built-in `django.contrib.auth.admin.UserAdmin`?

I mean, extending from `django.contrib.auth.admin.UserAdmin` and `django_reverse_admin.ReverseModelAdmin` at the same time.

**Comment by daniyalzade** [comment]
Can you please share the code for the models that you are building the admin interface for? I want to better understand how you are extending Django's user model.

**Comment by daniyalzade** [comment]
This has been open for a while, with no further information. Will close this.
