### ISSUE TITLE
Ability to remove attached inline

### ISSUE THREAD

**Issue by zenwalker** [daniyalzade/django_reverse_admin#66]
For now there’s no way to delete an inline once added (no remove checkbox is displayed). That would be really convenient if we had one.

**Comment by daniyalzade** [comment]
Fixed it @zenwalker. Thanks for the suggestion and please let me know if you run any issues while using it.

**Comment by v-erena** [comment]
In Django 3 the whole instance is removed when trying to remove an inline. I know that you currently support Django 2+. Any plans to also support Django 3?

**Comment by daniyalzade** [comment]
@v-erena can you please share an example? As far as I can see it works as expected.

Also, django 3 is already supported. Anything 2+ plus is supported

**Comment by v-erena** [comment]
Ah ok, cool, was reading it the way that 2+ covers versions of 2 but not 3. 

With your example setup, it works as expected. But with a more complicated model, if I want to delete an inline, I get 
```
AttributeError
'NoneType' object has no attribute 'attname'
/usr/local/lib/python3.8/site-packages/django/db/models/query_utils.py in _check_parent_chain, line 150
```
on Django 3.0 and python 3.8
This error message is not that helpful, I guess. I will dig deeper into that issue when I have time. Maybe I can reproduce the error with a simple example.
