### ISSUE TITLE
FieldError when ManyToMany and OneToOne to same class

### ISSUE THREAD

**Issue by xtompok** [daniyalzade/django_reverse_admin#68]
When I have class `Person` linking another class `Telephone` once as `OneToOneField` and once as `ManyToManyField`, then when trying to show admin site for `Person` with `OneToOneField` using django_reverse_admin an `FieldError` occurs.
Minimal example:
`myapp/models.py:`

    from django.db import models    
    class Telephone(models.Model):
        number = models.CharField(max_length=100)

    class Person(models.Model):
        home_phone = models.OneToOneField(Telephone, blank=True, null=True, on_delete=models.CASCADE,
                        related_name='person_home_phone_set')
        mobile_phones = models.ManyToManyField(Telephone, blank=True,
                        related_name='person_mobile_phone_set')

`myapp/admin.py:`

    from django.contrib import admin
    from django_reverse_admin import ReverseModelAdmin
    import myapp.models as m  

    class PhoneInline(admin.TabularInline):
        model = m.Telephone
    admin.site.register(m.Telephone)

    @admin.register(m.Person)
    class PersonAdmin(ReverseModelAdmin):
        base_model = m.Person
        inline_type = 'tabular'
        inline_reverse = ['home_phone']

If I edit line 70 of `django_remote_admin/__init__.py` to `(f.one_to_many or f.one_to_one or f.many_to_many) and f.auto_created and not f.concrete]` problem seems to be resolved, but I don't understand, what exactly is happening there and don't know if it doesn't break other things.

**Comment by daniyalzade** [comment]
Fixed it @xtompok . Thanks for the detailed report and please let me know if you run any issues while using it.
