### ISSUE TITLE
has_add_permissions is called in every case

### ISSUE THREAD

**Issue by spuetz** [daniyalzade/django_reverse_admin#81]
This line here calls `has_add_perm` in every case: https://github.com/daniyalzade/django_reverse_admin/blob/9c0eab18f27e2a6179dc09b36eb154df6ab165ea/django_reverse_admin/__init__.py#L208

This causes a `PermissionDenied` also if the change page is requested.

**Comment by spuetz** [comment]
The `has_add_permission` a view lines below is obsolete by this call, which shouldn't be the case, right?

**Comment by daniyalzade** [comment]
Thans for your note @spuetz . Just fixed it with 2.8.2.
